# Generated by Django 4.2.2 on 2023-06-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Btp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_male', models.SmallIntegerField(null=True)),
                ('is_phd', models.SmallIntegerField(null=True)),
                ('is_jammu', models.SmallIntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('result', models.FloatField(null=True)),
            ],
        ),
    ]
